[project]
name = 'Blockchain-Based-Specialized-Medical-Transportation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.driver-certification]
path = 'contracts/driver-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-registration]
path = 'contracts/patient-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.trip-coordination]
path = 'contracts/trip-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.vehicle-verification]
path = 'contracts/vehicle-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
